FROM adoptopenjdk/openjdk15:jdk-15.0.1_9-alpine AS builder

ARG VERSION=undef-version

ENV GRADLE_USER_HOME=/cache/_gradle

WORKDIR /src

#RUN ls -la /src
#RUN ls -la /cache
#RUN ls -la /cache/_gradle

#RUN id

RUN ./gradlew -Pversion=${VERSION} quarkusBuild --uber-jar



FROM adoptopenjdk/openjdk15:jdk-15.0.1_9-alpine AS link

ARG VERSION=undef-version

COPY build/dns-filter-${VERSION}-runner.jar /app.jar

VOLUME /opt/data/dns-filter

CMD ["java", "-jar", "/app.jar"]
