FROM adoptopenjdk/openjdk15:jdk-15.0.1_9-alpine

ARG VERSION=undef-version

ENV GRADLE_USER_HOME=/cache/_gradle

WORKDIR /src

#RUN ls -la /src
#RUN ls -la /cache
#RUN ls -la /cache/_gradle

#RUN id

RUN ./gradlew -Pversion=${VERSION} quarkusBuild --uber-jar


