# From https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Actions echo test

on: push

jobs:
  echo-job:
    name: Echoer
    runs-on: ubuntu-18.04
    steps:
    - name: print greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
        