name: ci

on:
  push:
    branches: [ container ]

jobs:
  login:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: modules/container/Containerfile
          push: true
          tags: jskov/test:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
