name: ci

on:
  push:
    branches: [ container ]

jobs:
  login:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test pull
        run: podman pull alpine:lastest

      - name: Test tag
        run: podman tag alpine:lastest docker.io/jskov/test

      - name: Test push
        run: podman push docker.io/jskov/test
