# From https://help.github.com/en/articles/workflow-syntax-for-github-actions
# Find actions in https://github.com/actions

# Gradle check does not return error on test failures.
# This allows test report to be collected before checking for success

name: Build and run tests


# Should work with both push and schedule, as per below, but does not.
# https://github.community/t5/GitHub-Actions/Multiple-event-triggers-with-config/m-p/33258

on:
  push
#  schedule:
#      - cron: '28 11 * * *'

jobs:
  build-job:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.x'
        architecture: x64
    - run: ./gradlew check
    - uses: actions/upload-artifact@v1
      with:
        name: server-test-report
        path: mods/server/build/reports
    - run: test -f mods/server/build/all-tests-passed
        