# From https://help.github.com/en/articles/workflow-syntax-for-github-actions
# Find actions in https://github.com/actions

name: Build and run tests

on: push

jobs:
  build-job:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.0.x'
        architecture: x64
    - run: ./gradlew check
    - uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: build/reports
        