# From https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Build and run tests

on: push

jobs:
  build-job:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@latest
    - uses: actions/setup-java@v1
      with:
        java-version: '12.0.x'
        architecture: x64
    - run: ./gradlew check
        